color issue

diff --git a/taskfiles/build.yml b/taskfiles/build.yml
--- a/taskfiles/build.yml
+++ b/taskfiles/build.yml
@@ -25,10 +25,10 @@ tasks:
         echo "PWD: $PWD"
         # install uv and uvx
         if [ -f "./bin/uv" ] && [ -x "./bin/uv" ]; then
-          printf "{{.BLUE}}[INFO] uv already present in ./bin, skipping installation{{.RESET}}\n"
+          printf "{{BLUE}}[INFO] uv already present in ./bin, skipping installation{{.RESET}}\n"
         else
-          printf "{{.BLUE}}Installing uv{{.RESET}}\n"
-          curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR="./bin" sh || { printf "{{.RED}}[ERROR] Failed to install uv{{.RESET}}\n"; exit 1; }
+          printf "{{BLUE}}Installing uv{{RESET}}\n"
+          curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR="./bin" sh || { printf "{{RED}}[ERROR] Failed to install uv{{.RESET}}\n"; exit 1; }
         fi
 
   install:
@@ -39,16 +39,15 @@ tasks:
         # we need the virtual environment at least for the tests to work
         # even if we don't install anything
 
-        # Create the virtual environment
         printf "${BLUE}[INFO] Creating virtual environment...${RESET}\n"
 
         # Create the virtual environment
         ./bin/uv venv --python 3.12 || { printf "${RED}[ERROR] Failed to create virtual environment${RESET}\n"; exit 1; }
 
         if [ -f "tests/requirements.txt" ]; then
-          ./bin/uv pip install -r tests/requirements.txt || { printf "{{.RED}}[ERROR] Failed to install test requirements{{.RESET}}\n"; exit 1; }
+          ./bin/uv pip install -r tests/requirements.txt || { printf "{{RED}}[ERROR] Failed to install test requirements{{.RESET}}\n"; exit 1; }
         fi
-        
+
         if [ -f "pyproject.toml" ]; then
           printf "${BLUE}[INFO] Installing dependencies${RESET}\n"
           ./bin/uv sync --all-extras --frozen || { printf "${RED}[ERROR] Failed to install dependencies${RESET}\n"; exit 1; }
